logo-light = "logo.svg"
logo-dark = "logo.svg"

[General]
index = "Intro"
blueprintsjs = "blueprints.js"

[Blueprints]
"blueprints/NativeToken" = "NativeToken"
"blueprints/ERC20" = "ERC20"
"blueprints/Basket" = "Basket"
"blueprints/ComposablePrediction" = "ComposablePrediction"
"blueprints/WithMetadata" = "WithMetadata"
"blueprints/UnsupportedBlueprint" = "UnsupportedBlueprint"
"blueprints/UnknownBlueprint" = "UnknownBlueprint"

[Oracles]
"oracles/ConstantOracle" = "ConstantOracle"
"oracles/MultisigOracle" = "MultisigOracle"
"oracles/UnsupportedOracle" = "UnsupportedOracle"
